model:  ["DSS"]
batch_size: [64]
emb_dim: [64]
drop_out: [0]
num_layers: [2,3,4,5]
num_mlp_layers: [2]
lr: [0.001]
JK: ["last"]

cat: [1]

epochs: [500]
drop_feat: [0]

lr_scheduler: ["ReduceLROnPlateau"]
lr_scheduler_decay_rate: [0.5]
lr_schedule_patience: [20]
min_lr: [0.00001]
