model:  ["GIN"]
batch_size: [128]
emb_dim: [128]
drop_out: [0]
num_layers: [4]
num_mlp_layers: [2]
pooling: ["sum"]
lr: [0.001]
JK: ["last"]

cat: [1]
spiderweb: [0]

epochs: [500]
drop_feat: [0]

lr_scheduler: ["ReduceLROnPlateau"]
lr_scheduler_decay_rate: [0.5]
lr_schedule_patience: [20]
min_lr: [0.00001]
