model:  ["GIN"]
batch_size: [128]
emb_dim: [300]
drop_out: [0]
num_layers: [10]
num_mlp_layers: [2]
pooling: ["mean"]
lr: [0.001]

cat: [1]

epochs: [500]
drop_feat: [0]

lr_scheduler: ["ReduceLROnPlateau"]
lr_scheduler_decay_rate: [0.5]
lr_schedule_patience: [20]
min_lr: [0.00001]
